# Generated by Django 4.0.4 on 2022-05-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomb', '0002_category_location_image_category_image_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='Media/'),
        ),
    ]
