# Generated by Django 4.0.4 on 2022-05-31 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bomb', '0004_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Location_name',
            new_name='location_name',
        ),
    ]
