# Generated by Django 4.0.4 on 2022-05-31 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bomb', '0005_rename_location_name_location_location_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_name',
            new_name='Location_name',
        ),
    ]
